site_name: Herb Classifier API

theme:
  name: material
  language: en
  palette:
    primary: deep-purple
    accent: deep-orange

plugins:
  - mkdocstrings

nav:
  - Documentation: index.md
  - Tutorials: tutorials.md
  - About: about.md
