site_name: Herb Classifier API

theme:
  name: material
  language: en
  palette:
    primary: deep-purple
    accent: deep-orange



nav:
  - index.md
  - tutorials.md
  - how-to-guides.md
  - reference.md
  - explanation.md
