site_name: Herb Classifier API

theme:
  name: material
  language: en
  palette:
    primary: green
    accent: yellow

plugins:
  - mkdocstrings

nav:
  - Documentation: index.md
  - Getting Started: getting_started.md
  - Installation: installation.md
  - Tutorials: tutorials.md
  - About: about.md
