site_name: Herb Classifier API

theme:
  name: material
  language: en
  palette:
    primary: deep-purple
    accent: deep-orange

plugins:
  - mkdocstrings

nav:
  - Documentation: index.md
  - Tutorial: tutorials.md
  - how-to-guides.md
  - reference.md
  - explanation.md
